# Generated by Django 6.0.6 on 2026-06-17 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('client', 'Client'), ('utilisateur', 'Utilisateur')], default='utilisateur', max_length=20),
        ),
    ]
